### ISSUE TITLE
Upload 0.1 to the cheeseshop

### ISSUE THREAD

**Issue by funkyfuture** [telota/rasmipy#7]
before starting the rest-api, i bumped to `0.1`. please fetch that tag, checkout and upload it to the PyPI.

**Comment by suchmaske** [comment]
I bumped it to 0.2 since you were so kind to implement the REST-API so quickly.

**Comment by suchmaske** [comment]
0.2 has been uploaded the PyPi but the install of the REST-API doesn't seem to work.

**Comment by suchmaske** [comment]
There was a typo in the readme. "ramsipy" instead of "rasmipy".

**Comment by funkyfuture** [comment]
i addressed both issues and pushed it to master.

i'm not 100% sure that the missing `requirements.txt` was the cause. thus trying with the testing pypi first seems reasonable.

**Comment by funkyfuture** [comment]
the typo is fixed, the installation issue -> #9
